spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AppdHome
    username: postgres
    password: Basededatos
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibertnate:
        jdbc:
          lob:
            non-contextual-creation: true